export const dummy = {
  dates: { maximum: "2023-09-11", minimum: "2023-07-25" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg",
      genre_ids: [28, 878, 27],
      id: 615656,
      original_language: "en",
      original_title: "Meg 2: The Trench",
      overview:
        "전 세계에서 가장 깊은 마리아나 해구, 역사상 가장 거대하고 무자비한 포식자가 도사리는 그곳에서 강철 다이버 ‘조나스’(제이슨 스타뎀)가 더 맹렬하게 돌아온 ‘메가로돈’과 짜릿한 대결을 펼치는 액션 어드벤처",
      popularity: 2943.17,
      poster_path: "/cbAHK6Vrt0GClMRUxH8TsgC2JqL.jpg",
      release_date: "2023-08-02",
      title: "메가로돈 2",
      video: true,
      vote_average: 7,
      vote_count: 1661,
    },
    {
      adult: false,
      backdrop_path: "/ctMserH8g2SeOAnCw5gFjdQF8mo.jpg",
      genre_ids: [35, 12, 14],
      id: 346698,
      original_language: "en",
      original_title: "Barbie",
      overview:
        "원하는 무엇이든 될 수 있는 바비랜드에서 살아가던 바비가 현실 세계와 이어진 포털의 균열을 발견하게 되고, 이를 해결하기 위해 켄과 예기치 못한 여정을 떠나면서 펼쳐지는 이야기",
      popularity: 3792.387,
      poster_path: "/rt8sHzR0XUyKHxU75ZIWs7MsNEN.jpg",
      release_date: "2023-07-19",
      title: "바비",
      video: false,
      vote_average: 7.3,
      vote_count: 4208,
    },
    {
      adult: false,
      backdrop_path: "/53z2fXEKfnNg2uSOPss2unPBGX1.jpg",
      genre_ids: [27, 9648, 53],
      id: 968051,
      original_language: "en",
      original_title: "The Nun II",
      overview:
        "1956년, 프랑스의 한 성당에서 신부가 끔찍하게 살해당한다. 이 사건을 조사하기 위해 파견된 아이린 수녀는 4년 전 자신을 공포에 떨게 했던 악마의 기운을 느낀다. 어두운 밤, 계속해서 일어나는 의문의 사건들 가운데 충격적인 진실이 드러나는데…",
      popularity: 2050.948,
      poster_path: "/hx4R7GqhiUP2LHJZJNrzCIqadd3.jpg",
      release_date: "2023-09-06",
      title: "더 넌 2",
      video: false,
      vote_average: 6.8,
      vote_count: 110,
    },

    {
      adult: false,
      backdrop_path: "/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg",
      genre_ids: [16, 35, 10751, 14, 10749],
      id: 976573,
      original_language: "en",
      original_title: "Elemental",
      overview:
        "불, 물, 공기, 흙 4개의 원소들이 살고 있는 엘리멘트 시티. 재치 있고 불처럼 열정 넘치는 앰버는 어느 날 우연히 유쾌하고 감성적이며 물 흐르듯 사는 웨이드를 만나 특별한 우정을 쌓으며, 지금껏 믿어온 모든 것들이 흔들리는 새로운 경험을 하게 되는데...",
      popularity: 1105.564,
      poster_path: "/1YYL1OcgjPLjAGi6n0iZe1gdl9i.jpg",
      release_date: "2023-06-14",
      title: "엘리멘탈",
      video: false,
      vote_average: 7.8,
      vote_count: 1866,
    },
    {
      adult: false,
      backdrop_path: "/w2nFc2Rsm93PDkvjY4LTn17ePO0.jpg",
      genre_ids: [16, 35, 28],
      id: 614930,
      original_language: "en",
      original_title: "Teenage Mutant Ninja Turtles: Mutant Mayhem",
      overview:
        "뉴욕의 하수구로 스며든 미스터리한 녹색 액체, ‘우즈’로 인해 아기 거북이 네 마리와 청년 쥐 스플린터는 사람과 비슷한 모습의 돌연변이가 된다. 15년 후, 10대 청소년이 된 레오나르도, 미켈란젤로, 라파엘, 도나텔로는 하수구에 숨어 사는 생활에서 벗어나 인간 세상에서 평범한 삶을 살고 싶어하고 우연히 만난 학생 기자 에이프릴과 함께 도시를 위협하는 '슈퍼플라이'와 그 일당을 물리치면 뉴욕의 히어로가 되어 당당히 세상에 나갈 수 있을 거라는 꿈을 꾸는데… 인간들을 모두 돌연변이로 만들겠다는 ‘슈퍼플라이’의 음모로 위험에 빠진 뉴욕! 틴에이저 히어로로 다시 태어난 ‘닌자터틀’ 형제들의 스트릿 액션 어드벤처가 펼쳐진다!",
      popularity: 887.868,
      poster_path: "/6xORIhe6cP3iM5RYTHs7MTOH1qa.jpg",
      release_date: "2023-07-31",
      title: "닌자터틀: 뮤턴트 대소동",
      video: false,
      vote_average: 7.2,
      vote_count: 417,
    },
    {
      adult: false,
      backdrop_path: "/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
      genre_ids: [28, 12, 878],
      id: 667538,
      original_language: "en",
      original_title: "Transformers: Rise of the Beasts",
      overview:
        "전 우주의 행성을 집어삼키는 절대자, ‘유니크론’의 부하 ‘스커지’는 ‘테러콘’들을 이끌고 지구에 당도한다. 그에 맞서기 위해 지구에 정체를 숨기고 있던 트랜스포머 ‘오토봇’ 군단이 모습을 드러내고 또 다른 트랜스포머 진영인 ‘맥시멀’과 힘을 합친다. 옵티머스 프라임이 이끄는 ‘오토봇’과 옵티머스 프라이멀을 중심으로 한 ‘맥시멀’. 모두의 운명을 건 그들의 압도적 전투가 시작된다!",
      popularity: 783.515,
      poster_path: "/chUZNPNd7EiETSB4xBGykXhuXRr.jpg",
      release_date: "2023-06-06",
      title: "트랜스포머: 비스트의 서막",
      video: false,
      vote_average: 7.5,
      vote_count: 3127,
    },
    {
      adult: false,
      backdrop_path: "/qEm4FrkGh7kGoEiBOyGYNielYVc.jpg",
      genre_ids: [27, 14],
      id: 635910,
      original_language: "en",
      original_title: "The Last Voyage of the Demeter",
      overview:
        "브램 스토커의 소설인 <드라큘라> 중 한 에피소드를 영화화하는 작품으로 드라큘라의 관을 싣고 가던 영국 배의 선원들이 차례로 사라지는 공포스러운 상황에 관한 이야기",
      popularity: 646.872,
      poster_path: "/nrtbv6Cew7qC7k9GsYSf5uSmuKh.jpg",
      release_date: "2023-08-09",
      title: "데메테르호의 마지막 항해",
      video: false,
      vote_average: 7.4,
      vote_count: 550,
    },
    {
      adult: false,
      backdrop_path: "/3mrli3xsGrAieQks7KsBUm2LpCg.jpg",
      genre_ids: [28, 80, 53],
      id: 979275,
      original_language: "en",
      original_title: "Mob Land",
      overview: "",
      popularity: 656.509,
      poster_path: "/yMu1g7A26N6wRFNwSwC7FOcfmCR.jpg",
      release_date: "2023-08-04",
      title: "Mob Land",
      video: false,
      vote_average: 6,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: "/AeR5k8Sp3zc2Ql4tT6CmgqspsEq.jpg",
      genre_ids: [12, 10751, 14, 10749],
      id: 447277,
      original_language: "en",
      original_title: "The Little Mermaid",
      overview:
        "아틀란티카 바다의 왕 트라이튼의 사랑스러운 막내딸인 인어 에리얼은 늘 인간들이 사는 바다 너머 세상으로의 모험을 꿈꾼다. 어느 날, 우연히 바다 위로 올라갔다가 폭풍우 속 가라앉는 배에 탄 인간 에릭 왕자의 목숨을 구해준다. 갈망하던 꿈과 운명적인 사랑을 이루기 위해 용기를 낸 에리얼은 사악한 바다 마녀 울슐라와의 위험한 거래를 통해 다리를 얻게 된다. 드디어 바다를 벗어나 그토록 원하던 인간 세상으로 가게 되지만, 그 선택으로 에리얼과 아틀란티카 왕국 모두 위험에 처하게 되는데… 바닷속, 그리고 그 너머 아름다운 꿈과 사랑의 멜로디가 펼쳐진다!",
      popularity: 601.121,
      poster_path: "/do9pxOrrFqgyebHwxj2IYtZXQIp.jpg",
      release_date: "2023-05-18",
      title: "인어공주",
      video: false,
      vote_average: 6.6,
      vote_count: 1943,
    },
    {
      adult: false,
      backdrop_path: "/rTJ8LLzT9NPRJA2dnQs0241bMRn.jpg",
      genre_ids: [27, 53],
      id: 1008042,
      original_language: "en",
      original_title: "Talk to Me",
      overview: "",
      popularity: 978.79,
      poster_path: "/kdPMUMJzyYAc4roD52qavX0nLIC.jpg",
      release_date: "2023-07-26",
      title: "톡 투 미",
      video: false,
      vote_average: 7.1,
      vote_count: 332,
    },
    {
      adult: false,
      backdrop_path: "/rRcNmiH55Tz0ugUsDUGmj8Bsa4V.jpg",
      genre_ids: [35, 10749],
      id: 884605,
      original_language: "en",
      original_title: "No Hard Feelings",
      overview:
        "집을 잃을 위기에 처한 매디는 돈을 벌기 위해 내성적이고 어색한 성격의 부잣집 아들과 데이트를 하기로 한다. 예상보다 쉽게 풀리지 않는 상황 속에서의 그녀의 여정이 펼쳐진다.",
      popularity: 486.613,
      poster_path: "/gD72DhJ7NbfxvtxGiAzLaa0xaoj.jpg",
      release_date: "2023-06-15",
      title: "노 하드 필링스",
      video: false,
      vote_average: 7.2,
      vote_count: 1214,
    },
    {
      adult: false,
      backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
      genre_ids: [18, 36],
      id: 872585,
      original_language: "en",
      original_title: "Oppenheimer",
      overview:
        "세상을 구하기 위해 세상을 파괴할 지도 모르는 선택을 해야 하는 천재 과학자의 핵개발 프로젝트.",
      popularity: 504.482,
      poster_path: "/4ZLnVUfiCe3wX8Ut9eyujndpyvA.jpg",
      release_date: "2023-07-19",
      title: "오펜하이머",
      video: false,
      vote_average: 8.3,
      vote_count: 3408,
    },
    {
      adult: false,
      backdrop_path: "/65rFnxzirxQDM0rYWmtAUYnjc.jpg",
      genre_ids: [27, 53],
      id: 1094713,
      original_language: "en",
      original_title: "The Mistress",
      overview: "",
      popularity: 382.497,
      poster_path: "/1kdmre0wlUAUk9BvySv4Xoveieg.jpg",
      release_date: "2023-07-28",
      title: "The Mistress",
      video: false,
      vote_average: 4.8,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
      genre_ids: [16, 10751, 12, 14, 35],
      id: 502356,
      original_language: "en",
      original_title: "The Super Mario Bros. Movie",
      overview:
        "따단-딴-따단-딴 ♫ 전 세계를 열광시킬 올 타임 슈퍼 어드벤처의 등장! 뉴욕의 평범한 배관공 형제 '마리오'와 ‘루이지’는 배수관 고장으로 위기에 빠진 도시를 구하려다 미스터리한 초록색 파이프 안으로 빨려 들어가게 된다. 파이프를 통해 새로운 세상으로 차원 이동하게 된 형제. 형 '마리오'는 뛰어난 리더십을 지닌 '피치'가 통치하는 버섯왕국에 도착하지만 동생 '루이지'는 빌런 '쿠파'가 있는 다크랜드로 떨어지며 납치를 당하고 ‘마리오’는 동생을 구하기 위해 ‘피치’와 ‘키노피오’의 도움을 받아 '쿠파'에 맞서기로 결심한다. 그러나 슈퍼스타로 세상을 지배하려는 그의 강력한 힘 앞에 이들은 예기치 못한 위험에 빠지게 되는데...!",
      popularity: 454.61,
      poster_path: "/dlGyzCxbBQK1U2O5o31Z1hB6erc.jpg",
      release_date: "2023-04-05",
      title: "슈퍼 마리오 브라더스",
      video: false,
      vote_average: 7.8,
      vote_count: 6573,
    },
    {
      adult: false,
      backdrop_path: "/4vlsYpItGVZN1UWZGqQBoCzrUSw.jpg",
      genre_ids: [53],
      id: 1030987,
      original_language: "en",
      original_title: "Sympathy for the Devil",
      overview:
        "'운전사'는 수상한 인물 \"승객\"에 의해 억지로 운전을 하게 되고, 자신이 큰 판돈이 걸린 추적 게임에 참여하게 되었음을 깨닫는다. 그들의 무시무시한 동행이 진행될수록, 모든 것이 보이는 것과 같지는 않다는 사실이 명백해진다.",
      popularity: 281.662,
      poster_path: "/afGdVMa80LMs6ibLP22CwM5uI4e.jpg",
      release_date: "2023-07-20",
      title: "심퍼시 포 더 데블",
      video: false,
      vote_average: 6.3,
      vote_count: 85,
    },
    {
      adult: false,
      backdrop_path: "/h0nmmdFAdBjQttN8Y0q825MWzZp.jpg",
      genre_ids: [28, 53, 80],
      id: 926393,
      original_language: "en",
      original_title: "The Equalizer 3",
      overview: "",
      popularity: 344.817,
      poster_path: "/p0WBnzgyqxMxbF4UGiqTwBLnwht.jpg",
      release_date: "2023-08-30",
      title: "더 이퀄라이저 3",
      video: false,
      vote_average: 6.8,
      vote_count: 149,
    },
    {
      adult: false,
      backdrop_path: "/AvSeU3ji59QLN2tfWXzVqI6hg8x.jpg",
      genre_ids: [27, 9648],
      id: 532408,
      original_language: "en",
      original_title: "The Boogeyman",
      overview:
        "‘세이디’와 어린 동생 ‘소여’는 갑작스러운 엄마의 사고로 깊은 슬픔에 빠진다. 그러던 어느날, 낯선 남자가 집에 찾아온 뒤부터 어둠 속에서 알 수 없는 존재가 나타나기 시작하는데… 6월 6일, 공포의 문이 열린다!",
      popularity: 297.621,
      poster_path: "/8qaKUHcTD4T2Xs43Y4MwvIKXnKb.jpg",
      release_date: "2023-05-31",
      title: "부기맨",
      video: false,
      vote_average: 6.8,
      vote_count: 355,
    },
    {
      adult: false,
      backdrop_path: "/jv4tiXAgaArMQo57jFMjvBEjmoa.jpg",
      genre_ids: [28, 18, 12],
      id: 980489,
      original_language: "en",
      original_title: "Gran Turismo",
      overview:
        "레이싱 게임 ‘그란 투리스모’의 덕후 ‘잔 마든보로’ 스피드라고는 게임으로만 만족해야 했던 그에게 레이싱 선수 발굴을 목표로 만들어진 ‘그란 투리스모 콘테스트’라는 기회가 찾아온다. 앉아서 게임만 하던 그의 앞에 닥친 혹독한 훈련과 치열한 경쟁.뛰어난 잠재력을 입증해 프로 레이싱 팀에 합류하는데 성공하지만 상대팀 선수들은 게이머 출신인 그를 인정하지 않고, 프로 레이싱의 세계는 그를 더욱 거칠게 몰아붙이는데...  리셋 버튼 없는 목숨을 건 실전! 게이머에서 레이서가 된 소년의 흥미로운 스토리가 스크린에서 펼쳐진다!",
      popularity: 320.134,
      poster_path: "/mewjjhpju5JT1wDFJDMdctWcCqd.jpg",
      release_date: "2023-08-09",
      title: "그란 투리스모",
      video: false,
      vote_average: 7.5,
      vote_count: 259,
    },
  ],
  total_pages: 96,
  total_results: 1907,
};
